apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: nginx
spec:
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer